
browser: Firefox
applicationUrl: https://www.freshworks.com/
chromeDriver: src/main/java/com/qa/lab/resources/webdrivers/chromedriver.exe
firefoxDriver: src/main/java/com/qa/lab/resources/webdrivers/geckodriver.exe
webDriverPageLoadTimeout: 20
webDriverImplicitTimeout: 10